### ISSUE TITLE
[Question]Chapter 10: Exercise 47 beyond the exercise 1

### ISSUE THREAD

**Issue by JessicaFeng0926** [reuven/python-workout#1]
Reuven,

你好！
I am reading python workout and I really like this book, especially the beyond the exercise part . But I found that I don't understand the first beyond the exercise question of Exercise 47. What is the attribute "self.returns" expected to contain? What does "a list of attribute names" indicate?
I  implemented my own "self.returns", but I am not sure whether it is correct.  Here is my code:

```
class Circle(CircleIterator):
      def __init__(self, data, number):
          super().__init__(data, number)
          self.returns = []
    
      def __next__(self):
          value = super().__next__()
          self.returns.append(value)
          return value
```
Could you please give me more information if it's not correct? Thanks a lot!

**Comment by sowmya-debug** [comment]
Hi Jessica,
In case you wish to follow what Reuven did,
`
c = Circle('abc', 5)
print(list(c))
`
Then your way defining `Circle` would return a non-iterable object.

`
class CircleIterator():
    def __init__(self, data, max_times):
        self.data = data
        self.max_times = max_times
        self.index = 0

    def __next__(self):
        if self.index >= self.max_times:
            raise StopIteration
        value = self.data[self.index % len(self.data)]
        self.index += 1
        return value
    
class Circle(CircleIterator):
    def __init__(self, data, number):
        super().__init__(data, number)
        self.returns = []
    
    def __next__(self):
        value = super().__next__()
        self.returns.append(value)
        return value

c = Circle('abc', 5)
print(list(c))
`

`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-b25f0afb11f2> in <module>
     23 
     24 c = Circle('abc', 5)
---> 25 print(list(c))

TypeError: 'Circle' object is not iterable
`

**Comment by JessicaFeng0926** [comment]
@sowmya-debug
Hi Sowmya,
Thank you for your reply. 
I read your code and I found that you missed the defination of __iter__(which should return self) in your CircleIterator class, that's why the Circle object was not iterable.  But I still don't know whether my implementation of self.returns is right or not. Do you have any idea about this exercise ?  I'll appreciate it if you could share your opinion with me.

**Comment by reuven** [comment]
@JessicaFeng0926 Sorry for not answering yet!  I appreciate your question, and will respond in the coming hours, when my students are solving another exercise.... (我真的不好意思!)

**Comment by JessicaFeng0926** [comment]
@reuven 
So glad to hear from you. 没事儿， 我不着急。

**Comment by reuven** [comment]
So, in the exercise (Circle), you created two classes: One (Circle) contains the data over which you'll be iterating, and the other (CircleIterator) is what `__iter__` returns. This is one way -- and, I'd argue, the preferred way -- to do things.

But there is another way, which I thought would be fun to play with. Namely, that instead of returning an instance of CircleIterator, you could just inherit from a more generic `Iterator` class. That is, any class that wants to be iterable can inherit from `Iterable`, and is iterable!

The problem with such an approach is that it's inherently generic. If you inherit from `Iterable`, then what is the data over which we're going to be iterating? That's defined in the subclass, not in the superclass.

So the idea is that `Circle` won't implement either `__iter__` or `__next__`. Those will both be implemented in `CircleIterator`, from which it inherits. But `CircleIterator` has to know what to return with each iteration. That'll be defined as the `returns` attribute on the subclass.

If we were in a language that typically used abstract base classes, then we could say that `CircleIterator` is such a class, and that it requires any subclass to define `requires` on the instance. But we're not, so it's all through conventions.

Now, in our case, we're just returning a single value with each iteration. So `returns` on the instance can be a list of a single element, a string indicating which attribute should be returned with each iteration. But you can imagine a situation (e.g., `enumerate`) in which you're getting two different values with each iteration. In such a case, `returns` would need to be a two-element list.  

So your solution doesn't quite match what I had in mind. But I think that what I had in mind wasn't super clear!  Let me know if you have more questions, and I'm really delighted that you're enjoying the book. I'm also happy to hear that you're enjoying the "beyond" exercises, which were an idea that Manning had, and which have turned out to be an unexpectedly popular option!

**Comment by JessicaFeng0926** [comment]
Hi Reuven, thank you for your patient reply! I know more about the purpose of this exercise after reading your explanation. 
I wrote my second solution.  This time, 
- my `CircleIterator` class is generic (I like the idea "generic")
- the `Circle` class doesn't implement `__iter__` or `__next__` 
- the `Circle` class has a 'self.returns' attribute

But I'm still not sure whether my implementation of `self.returns` is right. The problem is that my `self.returns` needs too much storage, because it contains all the items that need to be returned. 

Let me show you my code here:
```
class CircleIterator:
    def __init__(self):
        self.index = 0
        
    def __iter__(self):
        return self

    def __next__(self):
        # the self.returns attribute will 
        # be defined in subclasses
        if self.index >= len(self.returns):
            raise StopIteration
        value = self.returns[self.index]
        self.index += 1
        return value

class Circle(CircleIterator):
    def __init__(self, data, max_times):
        super().__init__()
        # the self.returns attribute contains 
        # all items that need to be returned
        self.returns = [data[time%len(data)] 
                        for time in range(max_times)]
```

Is this way of defining `self.returns` correct? Could you please give me more hints if it's still not right? Thank you so much!

**Comment by reuven** [comment]
@JessicaFeng0926 Ohhhhh that's not what I meant!  You're right, it could have been much clearer.

I thought that the `restores` attribute would contain one or more strings, indicating which attributes should be returned with each iteration.  For example, if you want to return the current value of the `x` attribute, you would set `self.returns = ['x']`. And if you want to return two attributes, `x` and `y`, you would set `self.returns = ['x', 'y']`.  Then, with each iteration, `self.__next__` would return the current value of `self.x`.  

The thing is, this is a bit more complex than I described, because I don't mention the use of `self.index`.  So you could (in one interpretation) say that `self.index` will be incremented with each iteration, and that `self.returns` will be a one-element list containing `self.data[self.index]`. Then you can run `eval` on that string.  Not ideal, but part of the point of these "beyond" exercises is to stretch the possibilities a bit, and experiment with some new techniques.

Honestly, there was some miscommunication and forgetfulness on my part, so I'm currently marching through all of the "beyond" exercises and am solving them myself, with a full set of solutions ready in the coming week or two (I hope).  When I get to this one, I'll try to think and rethink how I would solve it, and will include some ideas and notes in the comments.

**Comment by JessicaFeng0926** [comment]
@reuven 
I am looking forward to all of your solutions to the "beyond" exercises. I‘m so happy to see that you've already finished Chapter 1 and Chapter2! I solved all the problems by myself (except for this one),  and I know many of my solutions are not that good. I'm sure I will learn a lot by comparing your solutions with my own's. 
And for this exercise, I hope that you don't mind if I try the last time. 
```
class CircleIterator:
    def __init__(self, max_times):
        self.max_times = max_times
        self.index = 0
        
    def __iter__(self):
        return self

    def __next__(self):
        if self.index >= self.max_times:
            raise StopIteration
        # since the subclass is possible to return more than 
        # one element each iteration, so I use a list to collect
        # all the elements of one iteration
        values = []
        for attr_name in self.returns:
            attr_values = getattr(self, attr_name)
            values.append(attr_values[self.index%len(attr_values)])
        self.index += 1
        if len(values) == 1:
            return values[0]
        return values

class Circle(CircleIterator):
    def __init__(self, data, max_times):
        super().__init__(max_times)
        self.data = data
        self.returns = ['data']
```

Is it closer to what you expect us to do? If it's still very different from what you expect, I will just check this repository and wait for your solution instead of keeping asking questions,  because I feel that I took too much of your time! 非常感谢你的帮助 :-D

**Comment by reuven** [comment]
I'll take a look at your solution tomorrow and give some more suggestions. I was actually thinking a lot about this exercise over the weekend, and increasingly think that (a) I could have phrased the question better and (b) there are some other techniques I could use to fix this.  More to come soon on this answer, and yes, lots of additional solutions are coming soon, too!

**Comment by reuven** [comment]
Hi, @JessicaFeng0926 !  I haven't forgotten you; I just (a few minutes ago) finally finished all of the "beyond" code and added it to this repository.  Take a look at what I did for the `Circle` inheritance problem; it's not precisely the same as what I described, but it seems pretty close.  I hope that this helps!

**Comment by JessicaFeng0926** [comment]
@reuven Thank you so much! I will read your solution and give you feedback. 太感谢了！

**Comment by JessicaFeng0926** [comment]
@reuven I read your solution just now. I think I understand the whole idea now. It combines many Python features, that's cool! I’m interested in the code `return type(self)(self.data, self.max_times)`, I replaced this line with `return self`, and the program worked the same. So are there any differences between them? Or is that line just something for teaching?

**Comment by reuven** [comment]
There is a difference between the two approaches, but it's a subtle one.

It's the difference between returning a new iterator object each time you invoke `iter`, vs. getting the same object back each time.  Most of the time, it won't make a difference. Most of the time, you'll be just fine.

But often, it's better to get back a new object of the iterator. It's cleaner and makes sure that you don't have any state issues. And it's what a lot of built-in Python objects do -- look at what happens when you run `iter('abcd')` or `iter([10, 20, 30])`, and you'll see that you get a separate iterator object back, rather than the original object. But not everything works this way; files are an example of objects that are their own iterators.

**Comment by JessicaFeng0926** [comment]
@reuven 我明白了！To get back a new object of the iterator every time, I used to create two classes -- one for the iterable and the other for the iterator. It's so good to know a new way to achieve the same goal ! I have no more questions about this solution, it's a good exercise. Thank you for your help again!

**Comment by reuven** [comment]
Excellent; my pleasure. I'm closing this issue. Thanks for your patience while I got around to answering!
